url: "mongodb://root:techfinsd@172.17.101.11:27017/?authMechanism=SCRAM-SHA-1"
default-database: "en"
notebooks-database: "user_code_service"
symbol-database: "symbol_service"
max-connection-wait-time-seconds: 10
max-connection-pool-size: 10
