POST localhost:8080/run
Content-Type: application/json

"data_1"
###
POST localhost:8080/add
Content-Type: application/json

{
  "inputs": [
    "data_1",
    "data_2"
  ],
  "funcId": "func_id",
  "shapeRule": {
    "m": 242,
    "n": 1
  },
  "alignmentRule": {
    "offsets": {
      "data_1": 0,
      "data_2": 0
    }
  },
  "arguments": {
    "x": {
      "type": "float",
      "value": "42"
    }
  },
  "outputs": ["1", "2", "3"]
}
###
POST localhost:8080/update_func
Content-Type: application/json

"func_id"